[project]
name = "rota-demo"
version = "0.1.0"
description = "Demo version of rota management system"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.14.3",
    "bs4>=0.0.2",
    "freesimplegui==5.2.0",
    "loguru>=0.7.3",
    "numpy>=2.2.6",
    "pendulum>=3.2.0",
    "pyperclip>=1.11.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]
